import { SGrid } from "../components/style/SGrid";
import { SLead } from "../components/style/SLead";
import { ToolCard } from "../components/ToolCard";

export const Tools = () => {
    return (
        <div className="page-shell page-tools">
            <h1 className="section-heading">Tools</h1>
            <SLead>開発</SLead>
            <SGrid>
                <ToolCard
                    src={"https://img.icons8.com/color/96/python--v1.png"}
                    text={"Python"}
                    lev={":★★★☆☆"}
                    des={"ゲームを少し作成。言語モデルを使用した開発でも使用。"}
                />
                <ToolCard
                    src={"https://img.icons8.com/color/96/c-plus-plus-logo.png"}
                    text={"C++"}
                    lev={":★★★☆☆"}
                    des={"卒業研究、アルゴリズムの実装で使用。"}
                />
                <ToolCard
                    src={"https://img.icons8.com/color/96/html-5--v1.png"}
                    text={"html"}
                    lev={":★☆☆☆☆"}
                    des={"プレーンで使用することはほぼナシ。"}
                />
                <ToolCard
                    src={"https://img.icons8.com/color/96/css3.png"}
                    text={"CSS"}
                    lev={":★★☆☆☆"}
                    des={"プレーンで使用することはほぼナシ。"}
                />
                <ToolCard
                    src={"https://img.icons8.com/color/96/react-native.png"}
                    text={"react"}
                    lev={":★★★☆☆"}
                    des={"react, react nativeともに使用経験あり。"}
                />
                <ToolCard
                    src={"https://img.icons8.com/color/96/nextjs.png"}
                    text={"next"}
                    lev={":★★★☆☆"}
                    des={"インターンでの開発に使用。"}
                />
                <ToolCard
                    src={
                        "https://img.icons8.com/color/96/amazon-web-services.png"
                    }
                    text={"AWS"}
                    lev={":★★☆☆☆"}
                    des={"インターンでの開発と研究に使用。"}
                />
                <ToolCard
                    src={
                        "https://img.icons8.com/color/96/ruby-programming-language.png"
                    }
                    text={"Ruby"}
                    lev={":★☆☆☆☆"}
                    des={"Ruby on Railsでの開発経験あり。実用経験は全くない。"}
                />
            </SGrid>
            <SLead>その他</SLead>
            <SGrid>
                <ToolCard
                    src={
                        "https://img.icons8.com/fluency/96/microsoft-teams-2019.png"
                    }
                    text={"teams"}
                    lev={":★★★★☆"}
                />
                <ToolCard
                    src={"https://img.icons8.com/color/96/slack.png"}
                    text={"slack"}
                    lev={":★★★☆☆"}
                />
                <ToolCard
                    src={"https://img.icons8.com/fluency/96/canva.png"}
                    text={"canva"}
                    lev={":★★★☆☆"}
                />
                <ToolCard
                    src={"https://img.icons8.com/color/96/figma--v1.png"}
                    text={"Figma"}
                    lev={":★☆☆☆☆"}
                />
                <ToolCard
                    src={
                        "https://img.icons8.com/material-outlined/96/notion--v1.png"
                    }
                    text={"Notion"}
                    lev={":★★★☆☆"}
                />
                <ToolCard
                    src={"https://img.icons8.com/color/96/obsidian.png"}
                    text={"Obsidian"}
                    lev={":★★☆☆☆"}
                />
                <ToolCard
                    src={
                        "https://img.icons8.com/color/96/adobe-illustrator--v1.png"
                    }
                    text={"illustrater"}
                    lev={":★★★★☆"}
                />
                <ToolCard
                    src={
                        "https://img.icons8.com/color/96/adobe-premiere-pro--v1.png"
                    }
                    text={"PremierePro"}
                    lev={":★☆☆☆☆"}
                />
            </SGrid>
        </div>
    );
};
